In [21]:
import pandas as pd
import joblib
import yaml
from sklearn.model_selection import train_test_split
from ML.data import process_data
from ML.model import train_model, compute_model_metrics, inference, slice_data #, process_data

In [22]:
model = joblib.load("model/classifier_model.joblib")

In [23]:
#model = joblib.load('./model/classifier_model.joblib')

In [24]:
# Reading configuration file
with open('config.yaml') as f:
    config = yaml.load(f, Loader=yaml.FullLoader)

In [25]:
# loading in the data.
df = pd.read_csv('./data/census_clean.csv')

In [26]:
# categorical features in data
cat_features = config['data']['cat_features']

In [27]:
# save encoder and binarizer of the training data
encoder_train = joblib.load('./model/encoder_train.joblib')
lb_train = joblib.load('./model/lb_train.joblib')

In [28]:
# train-test split
train, test = train_test_split(df, test_size=config['model_training']['test_size'],
                               random_state=config['model_training']['random_state'],
                               stratify=df['salary'])

In [29]:
X_train, y_train, encoder, lb = process_data(
    test, categorical_features=cat_features,
    label="salary", training=False, encoder=encoder_train, lb=lb_train
)

In [30]:
preds = inference(model, X_train)#[0])#,:])

In [31]:
prediction = lb.inverse_transform(preds)#[9760]

In [32]:
prediction

array([' <=50K', ' <=50K', ' <=50K', ..., ' >50K', ' >50K', ' >50K'],
      dtype='<U6')

In [33]:
len(prediction)

9762

In [34]:
len(X_train)

9762

In [36]:
test.head(50)

,age,workclass,fnlgt,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,salary
6623,72,Self-emp-inc,473748,Some-college,Married-civ-spouse,Exec-managerial,Husband,White,Male,25,United-States,>50K
3688,30,Private,306383,Some-college,Divorced,Handlers-cleaners,Not-in-family,White,Male,50,United-States,<=50K
25741,22,Private,229987,Some-college,Never-married,Tech-support,Other-relative,Asian-Pac-Islander,Female,32,United-States,<=50K
2391,22,Private,189950,Bachelors,Never-married,Prof-specialty,Not-in-family,White,Male,55,United-States,<=50K
13787,46,Private,218329,Some-college,Never-married,Craft-repair,Own-child,White,Male,40,United-States,<=50K
2697,48,Private,320421,HS-grad,Married-civ-spouse,Sales,Husband,White,Male,50,United-States,<=50K
19322,23,Local-gov,210029,Some-college,Never-married,Adm-clerical,Own-child,White,Female,20,United-States,<=50K
15922,58,Private,126104,Masters,Divorced,Adm-clerical,Not-in-family,White,Female,45,United-States,<=50K
18568,23,Private,166527,Some-college,Never-married,Exec-managerial,Own-child,Other,Female,40,United-States,<=50K
18244,61,Local-gov,144723,Masters,Married-civ-spouse,Exec-managerial,Husband,White,Male,60,United-States,>50K
20504,51,State-gov,285747,Masters,Married-civ-spouse,Prof-specialty,Husband,White,Male,60,United-States,>50K
30222,47,Private,49298,HS-grad,Divorced,Sales,Not-in-family,White,Male,50,United-States,<=50K
15385,22,Private,401762,HS-grad,Never-married,Adm-clerical,Not-in-family,White,Female,55,United-States,<=50K
11814,36,State-gov,108320,Masters,Divorced,Prof-specialty,Unmarried,White,Male,30,United-States,<=50K
23098,38,Local-gov,177305,Bachelors,Married-civ-spouse,Prof-specialty,Husband,White,Male,38,United-States,<=50K
29415,18,?,25837,11th,Never-married,?,Own-child,White,Male,72,United-States,<=50K
9856,43,Self-emp-not-inc,355856,Bachelors,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,50,Philippines,<=50K
19500,27,?,173800,Masters,Never-married,?,Unmarried,Asian-Pac-Islander,Male,20,Taiwan,<=50K
10833,17,Private,126779,11th,Never-married,Other-service,Own-child,Black,Male,20,United-States,<=50K
31430,55,Local-gov,143949,Masters,Married-civ-spouse,Prof-specialty,Wife,White,Female,45,United-States,>50K
20893,34,Private,90614,Assoc-acdm,Married-civ-spouse,Tech-support,Husband,White,Male,10,United-States,<=50K
20943,22,State-gov,309348,Some-college,Never-married,Adm-clerical,Not-in-family,White,Female,15,United-States,<=50K
17090,30,Private,263150,HS-grad,Divorced,Machine-op-inspct,Unmarried,White,Female,20,United-States,<=50K
27823,35,Private,265662,Bachelors,Married-civ-spouse,Sales,Husband,White,Male,40,United-States,>50K
22512,37,Private,82576,Prof-school,Divorced,Prof-specialty,Not-in-family,White,Male,36,United-States,>50K
19788,58,Private,111625,Bachelors,Widowed,Exec-managerial,Unmarried,White,Male,40,United-States,>50K
19016,47,Private,155659,Some-college,Married-civ-spouse,Craft-repair,Husband,White,Male,55,United-States,>50K
25347,26,Private,108019,HS-grad,Never-married,Craft-repair,Own-child,White,Male,40,United-States,<=50K
20567,68,?,351402,Doctorate,Married-civ-spouse,?,Husband,White,Male,70,United-States,<=50K
21825,60,Self-emp-not-inc,264314,Some-college,Married-civ-spouse,Exec-managerial,Husband,White,Male,35,Columbia,<=50K
3736,36,?,53606,Assoc-voc,Married-civ-spouse,?,Wife,White,Female,8,United-States,<=50K
9020,45,Private,140644,HS-grad,Married-civ-spouse,Sales,Husband,White,Male,50,United-States,>50K
21443,34,?,170276,Bachelors,Married-civ-spouse,?,Wife,White,Female,10,United-States,>50K
29835,52,Private,90189,7th-8th,Divorced,Priv-house-serv,Own-child,Black,Female,16,United-States,<=50K
26491,25,Private,169679,HS-grad,Married-civ-spouse,Transport-moving,Husband,White,Male,40,United-States,<=50K
22980,59,Private,195820,HS-grad,Married-civ-spouse,Transport-moving,Husband,White,Male,40,United-States,>50K
24599,57,Self-emp-not-inc,152030,Some-college,Married-civ-spouse,Sales,Wife,White,Female,25,United-States,>50K
5686,41,Private,78410,HS-grad,Married-civ-spouse,Adm-clerical,Wife,White,Female,40,United-States,>50K
3095,48,Self-emp-inc,200471,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,40,United-States,>50K
10720,19,Private,41400,HS-grad,Never-married,Handlers-cleaners,Own-child,White,Male,30,United-States,<=50K
10573,51,Private,102615,Masters,Married-civ-spouse,Protective-serv,Husband,White,Male,40,United-States,>50K
32147,41,Private,151736,10th,Never-married,Machine-op-inspct,Not-in-family,White,Male,40,United-States,<=50K
20613,32,Private,226883,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,40,Germany,<=50K
18047,40,Private,175674,Bachelors,Married-civ-spouse,Sales,Husband,White,Male,50,United-States,>50K
1790,30,Federal-gov,188569,9th,Married-civ-spouse,Tech-support,Husband,White,Male,40,United-States,<=50K
14672,35,Self-emp-not-inc,216256,9th,Married-civ-spouse,Craft-repair,Husband,White,Male,50,United-States,<=50K
1108,41,Private,118212,Bachelors,Married-civ-spouse,Craft-repair,Husband,White,Male,40,United-States,>50K
21698,25,Private,108542,Bachelors,Never-married,Exec-managerial,Own-child,White,Male,35,United-States,<=50K
24312,48,Self-emp-not-inc,52240,Assoc-voc,Married-civ-spouse,Exec-managerial,Wife,White,Female,25,United-States,>50K
28589,40,Self-emp-not-inc,29036,Some-college,Never-married,Machine-op-inspct,Not-in-family,White,Male,35,United-States,<=50K